### ISSUE TITLE
Client error response [status code] 422

### ISSUE THREAD

**Issue by stijnb1234** [xsolla/xsolla-sdk-php#79]
I get this error when creating a client:

Fatal error: Uncaught Guzzle\Http\Exception\ClientErrorResponseException: Client error response [status code] 422 [reason phrase] Unprocessable Entity [url] https://api.xsolla.com/merchant/merchants/xxxxxx/token in E:\xampppp\htdocs\vendor\guzzle\guzzle\src\Guzzle\Http\Exception\BadResponseException.php:43 Stack trace: #0 E:\xampppp\htdocs\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 E:\xampppp\htdocs\vendor\symfony\event-dispatcher\EventDispatcher.php(184): Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 E:\xampppp\htdocs\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) #3 E:\xampppp\htdocs\vendor\guzzle\guzzle\src\Guzzle\Http\Message\

How to fix?

**Comment by Nalik27** [comment]
++ Такая же ошибка.. Как решить?
